/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */







declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
}

export interface NexusGenEnums {
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
}

export interface NexusGenObjects {
  Fruits: { // root type
    amount?: number | null; // Int
    description?: string | null; // String
    id?: string | null; // String
    limitOfFruitToBeStored?: number | null; // Int
    name?: string | null; // String
  }
  Mutation: {};
  Query: {};
  Response: { // root type
    data?: Array<NexusGenRootTypes['Fruits'] | null> | null; // [Fruits]
    message?: string | null; // String
    status?: string | null; // String
  }
}

export interface NexusGenInterfaces {
}

export interface NexusGenUnions {
}

export type NexusGenRootTypes = NexusGenObjects

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars

export interface NexusGenFieldTypes {
  Fruits: { // field return type
    amount: number | null; // Int
    description: string | null; // String
    id: string | null; // String
    limitOfFruitToBeStored: number | null; // Int
    name: string | null; // String
  }
  Mutation: { // field return type
    createFruitForFruitStorage: NexusGenRootTypes['Response'] | null; // Response
    deleteFruitFromFruitStorage: NexusGenRootTypes['Response'] | null; // Response
    removeFruitFromFruitStorage: NexusGenRootTypes['Response'] | null; // Response
    storeFruitToFruitStorage: NexusGenRootTypes['Response'] | null; // Response
    updateFruitForFruitStorage: NexusGenRootTypes['Response'] | null; // Response
  }
  Query: { // field return type
    findFruit: NexusGenRootTypes['Response']; // Response!
    getFruitStorage: NexusGenRootTypes['Response'] | null; // Response
  }
  Response: { // field return type
    data: Array<NexusGenRootTypes['Fruits'] | null> | null; // [Fruits]
    message: string | null; // String
    status: string | null; // String
  }
}

export interface NexusGenFieldTypeNames {
  Fruits: { // field return type name
    amount: 'Int'
    description: 'String'
    id: 'String'
    limitOfFruitToBeStored: 'Int'
    name: 'String'
  }
  Mutation: { // field return type name
    createFruitForFruitStorage: 'Response'
    deleteFruitFromFruitStorage: 'Response'
    removeFruitFromFruitStorage: 'Response'
    storeFruitToFruitStorage: 'Response'
    updateFruitForFruitStorage: 'Response'
  }
  Query: { // field return type name
    findFruit: 'Response'
    getFruitStorage: 'Response'
  }
  Response: { // field return type name
    data: 'Fruits'
    message: 'String'
    status: 'String'
  }
}

export interface NexusGenArgTypes {
  Mutation: {
    createFruitForFruitStorage: { // args
      description?: string | null; // String
      limitOfFruitToBeStored?: number | null; // Int
      name: string; // String!
    }
    deleteFruitFromFruitStorage: { // args
      forceDelete?: boolean | null; // Boolean
      name: string; // String!
    }
    removeFruitFromFruitStorage: { // args
      amount?: number | null; // Int
      name: string; // String!
    }
    storeFruitToFruitStorage: { // args
      amount?: number | null; // Int
      name: string; // String!
    }
    updateFruitForFruitStorage: { // args
      description?: string | null; // String
      limitOfFruitToBeStored?: number | null; // Int
      name: string; // String!
    }
  }
  Query: {
    findFruit: { // args
      name: string; // String!
    }
  }
}

export interface NexusGenAbstractTypeMembers {
}

export interface NexusGenTypeInterfaces {
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = never;

export type NexusGenEnumNames = never;

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = never;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = never;

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    isTypeOf: false
    resolveType: true
    __typename: false
  }
}

export interface NexusGenTypes {
  context: any;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginInputTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
  interface NexusGenPluginArgConfig {
  }
}